#!/usr/bin/env bash
# Generated by scripts/sync_adapters.py; do not edit by hand.
set -euo pipefail

prefix="${HOME}/.config/opencode"
dry_run=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --prefix)
      prefix="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

config="${prefix}/opencode.json"

if [ "$dry_run" = "1" ]; then
  echo "uninstall_prefix=${prefix}"
  echo "config=${config}"
  exit 0
fi

rm -rf "${prefix}/skills/llm-wiki-cloud-mount"
rm -rf "${prefix}/skills/llm-wiki-cloud-query"
rm -rf "${prefix}/skills/llm-wiki-cloud-backflow"

python3 - "$config" "cann-infer-wiki-cloud" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
mcp_server_name = sys.argv[2]

if not config_path.exists():
    raise SystemExit(0)

data = json.loads(config_path.read_text(encoding="utf-8"))
mcp = data.get("mcp")
if isinstance(mcp, dict):
    mcp.pop(mcp_server_name, None)

config_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY

echo "Uninstalled llm-wiki-client OpenCode adapter from ${prefix}"
