from pathlib import Path
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKDOWN_MARKER = "<!-- Generated by scripts/sync_adapters.py; do not edit by hand. -->"
TOKEN_PATTERN = re.compile(r"llmw_[A-Za-z0-9_=-]{12,}")


def copy_path(src: Path, dst: Path) -> None:
    if src.is_dir():
        shutil.copytree(
            src,
            dst,
            ignore=shutil.ignore_patterns(".git", ".idea", "__pycache__"),
            dirs_exist_ok=True,
        )
        return

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


class SourceLayoutTests(unittest.TestCase):
    def test_version_and_constants_exist(self):
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        constants = json.loads((ROOT / "src/shared/constants.json").read_text(encoding="utf-8"))
        self.assertRegex(version, r"^\d+\.\d+\.\d+$")
        self.assertEqual(constants["version"], version)
        self.assertEqual(constants["plugin_name"], "llm-wiki-client")
        self.assertEqual(constants["marketplace_name"], "llm-wiki-cloud-test")
        self.assertEqual(constants["test_repository"], "AndyKong2020/LLM-Wiki-Marketplace-Multiclient-Test")
        self.assertEqual(constants["test_ref"], "main")
        self.assertEqual(constants["mcp_url"], "https://wiki.andykong.top/mcp")
        self.assertEqual(constants["backflow_upload_url"], "https://wiki.andykong.top/upload/backflow")
        self.assertEqual(constants["version_manifest_url"], "https://wiki.andykong.top/plugin/llm-wiki-client/version.json")

    def test_pin_block_template_has_platform_slots(self):
        text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("{{instruction_file}}", text)
        self.assertIn("{{mcp_url}}", text)
        self.assertIn("{{query_skill_name}}", text)
        self.assertIn("{{wiki_search_tool}}", text)
        self.assertIn("{{wiki_get_page_tool}}", text)


class TemplateInventoryTests(unittest.TestCase):
    def test_skill_templates_do_not_reference_legacy_query_skill(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("llm-wiki-query", text, path.relative_to(ROOT))

    def test_shared_skill_templates_are_platform_neutral(self):
        forbidden_phrases = [
            "当前 Claude Code 项目目录",
            "/plugin update",
            "/reload-plugins",
            "claude mcp add",
        ]
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            for phrase in forbidden_phrases:
                with self.subTest(path=path.relative_to(ROOT), phrase=phrase):
                    self.assertNotIn(phrase, text)

    def test_mount_template_uses_shared_pin_block_contract(self):
        mount_text = (ROOT / "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl").read_text(encoding="utf-8")
        pin_block_text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("src/shared/pin-block.md.tmpl", mount_text)
        for slot in set(re.findall(r"{{[a-zA-Z0-9_]+}}", pin_block_text)):
            with self.subTest(slot=slot):
                self.assertIn(slot, mount_text)

    def test_skill_templates_have_no_todo_markers(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("TODO", text, path.relative_to(ROOT))

    def test_required_templates_exist(self):
        required = [
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
            "platforms/claude/marketplace.json.tmpl",
            "platforms/claude/plugin.json.tmpl",
            "platforms/codex/marketplace.json.tmpl",
            "platforms/codex/plugin.json.tmpl",
            "platforms/opencode/opencode.json.tmpl",
            "platforms/opencode/bootstrap.sh.tmpl",
            "platforms/opencode/install-opencode.sh.tmpl",
            "platforms/opencode/uninstall.sh.tmpl",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                path = ROOT / rel
                self.assertTrue(path.exists(), rel)
                self.assertGreater(path.stat().st_size, 80, rel)

    def test_no_command_source_or_adapter_dirs(self):
        forbidden = [
            "src/commands",
            "plugins/llm-wiki-client-claude/commands",
            "plugins/llm-wiki-client-codex/commands",
            "plugins/llm-wiki-client-opencode/commands",
        ]
        for rel in forbidden:
            with self.subTest(rel=rel):
                self.assertFalse((ROOT / rel).exists(), rel)

    def test_skill_templates_have_required_frontmatter_slots(self):
        for rel in [
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
        ]:
            text = (ROOT / rel).read_text(encoding="utf-8")
            self.assertIn("version: {{version}}", text)
            self.assertIn("name:", text)
            self.assertIn("description:", text)

    def test_distribution_plan_does_not_embed_realistic_upload_tokens(self):
        plan_path = ROOT / "docs/superpowers/plans/2026-06-01-multiclient-distribution-implementation.md"
        text = plan_path.read_text(encoding="utf-8")
        self.assertIsNone(TOKEN_PATTERN.search(text), plan_path.relative_to(ROOT))


class SyncAdaptersTests(unittest.TestCase):
    FIXTURE_PATHS = [
        "VERSION",
        "src",
        "platforms",
        "scripts/sync_adapters.py",
        ".claude-plugin",
        "plugins/llm-wiki-client-claude/.claude-plugin",
        "plugins/llm-wiki-client-claude/.mcp.json",
        "plugins/llm-wiki-client-claude/skills",
        "plugins/llm-wiki-client-codex",
        "plugins/llm-wiki-client-opencode",
    ]

    def copy_repo_fixture(self) -> Path:
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        temp_root = Path(temp_dir.name)
        for rel in self.FIXTURE_PATHS:
            copy_path(ROOT / rel, temp_root / rel)
        return temp_root

    def copy_script_only_fixture(self) -> Path:
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        script_root = Path(temp_dir.name)
        copy_path(ROOT / "scripts/sync_adapters.py", script_root / "scripts/sync_adapters.py")
        return script_root

    def run_sync(self, temp_root: Path | None = None) -> Path:
        temp_root = temp_root or self.copy_repo_fixture()
        env = os.environ.copy()
        env["LLM_WIKI_REPO_ROOT"] = str(temp_root)
        subprocess.run([sys.executable, "scripts/sync_adapters.py"], cwd=temp_root, env=env, check=True)
        self.sync_root = temp_root
        return temp_root

    def test_sync_uses_env_root_when_script_path_is_outside_repo_fixture(self):
        temp_root = self.copy_repo_fixture()
        script_root = self.copy_script_only_fixture()
        env = os.environ.copy()
        env["LLM_WIKI_REPO_ROOT"] = str(temp_root)

        subprocess.run(
            [sys.executable, str(script_root / "scripts/sync_adapters.py")],
            cwd=script_root,
            env=env,
            check=True,
        )

        self.assertTrue((temp_root / "plugins/llm-wiki-client-opencode/opencode.json").exists())
        self.assertFalse((script_root / "plugins/llm-wiki-client-opencode/opencode.json").exists())

    def test_run_sync_does_not_create_live_stale_test_paths(self):
        live_test_paths = [
            ROOT / ".agents/unmanaged/sentinel.txt",
            ROOT / "plugins/llm-wiki-client-claude/skills/stale-generated/SKILL.md",
            ROOT / "plugins/llm-wiki-client-claude/skills/stale-user/SKILL.md",
        ]
        live_state = {path: path.read_bytes() if path.is_file() else None for path in live_test_paths}

        temp_root = self.run_sync()

        self.assertNotEqual(temp_root.resolve(), ROOT.resolve())
        for path, original_content in live_state.items():
            with self.subTest(path=path.relative_to(ROOT)):
                current_content = path.read_bytes() if path.is_file() else None
                self.assertEqual(current_content, original_content)

    def test_sync_preserves_unmanaged_agents_files(self):
        temp_root = self.copy_repo_fixture()
        sentinel = temp_root / ".agents/unmanaged/sentinel.txt"
        sentinel_text = "unmanaged agent state must survive sync\n"
        sentinel.parent.mkdir(parents=True, exist_ok=True)
        sentinel.write_text(sentinel_text, encoding="utf-8")

        self.run_sync(temp_root)

        self.assertTrue(sentinel.exists())
        self.assertEqual(sentinel.read_text(encoding="utf-8"), sentinel_text)

    def test_sync_removes_stale_generated_marked_files(self):
        temp_root = self.copy_repo_fixture()
        stale_generated = temp_root / "plugins/llm-wiki-client-claude/skills/stale-generated/SKILL.md"
        stale_user = temp_root / "plugins/llm-wiki-client-claude/skills/stale-user/SKILL.md"
        stale_generated.parent.mkdir(parents=True, exist_ok=True)
        stale_user.parent.mkdir(parents=True, exist_ok=True)
        stale_generated.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated skill\n", encoding="utf-8")
        stale_user.write_text("user managed skill\n", encoding="utf-8")

        self.run_sync(temp_root)

        self.assertFalse(stale_generated.exists())
        self.assertTrue(stale_user.exists())

    def test_sync_removes_stale_generated_skill_files(self):
        temp_root = self.copy_repo_fixture()
        stale_skill = temp_root / "plugins/llm-wiki-client-claude/skills/stale/SKILL.md"
        stale_skill.parent.mkdir(parents=True, exist_ok=True)
        stale_skill.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated skill\n", encoding="utf-8")

        self.run_sync(temp_root)

        self.assertFalse(stale_skill.exists())

    def test_sync_generates_all_platform_entrypoints(self):
        temp_root = self.run_sync()
        required = [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client-claude/.mcp.json",
            "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client-codex/.mcp.json",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client-opencode/opencode.json",
            "plugins/llm-wiki-client-opencode/bootstrap.sh",
            "plugins/llm-wiki-client-opencode/install-opencode.sh",
            "plugins/llm-wiki-client-opencode/uninstall.sh",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-backflow/SKILL.md",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                self.assertTrue((temp_root / rel).exists(), rel)

    def test_sync_replaces_all_template_variables(self):
        temp_root = self.run_sync()
        generated = [
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]
        for rel in generated:
            path = temp_root / rel
            self.assertTrue(path.exists(), rel)
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("{{", text)
            self.assertNotIn("}}", text)
            self.assertIn("version: 1.1.6", text)
            self.assertIn("https://wiki.andykong.top/mcp", text)

    def test_sync_generates_platform_specific_instruction_targets(self):
        temp_root = self.run_sync()
        claude_mount = (temp_root / "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        codex_mount_path = temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        opencode_mount = (temp_root / "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("CLAUDE.md", claude_mount)
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("AGENTS.md", opencode_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", opencode_mount)

    def test_sync_generates_codex_specific_skill_root(self):
        temp_root = self.run_sync()
        codex_manifest = json.loads(
            (temp_root / "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json").read_text(encoding="utf-8")
        )
        self.assertIn("skills", codex_manifest)
        self.assertEqual(codex_manifest["skills"], "./skills/")
        self.assertFalse((temp_root / "plugins/llm-wiki-client-codex/codex").exists())
        self.assertFalse((temp_root / "plugins/llm-wiki-client-codex/commands").exists())

        codex_mount_path = temp_root / "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("cann-infer-wiki-cloud wiki_search", codex_mount)
        self.assertNotIn("CLAUDE.md", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)

    def test_sync_generates_valid_json_manifests(self):
        temp_root = self.run_sync()
        for rel in [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client-claude/.mcp.json",
            "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client-codex/.mcp.json",
            "plugins/llm-wiki-client-opencode/opencode.json",
        ]:
            with self.subTest(rel=rel):
                json.loads((temp_root / rel).read_text(encoding="utf-8"))

    def test_sync_preserves_markdown_frontmatter(self):
        temp_root = self.run_sync()
        for rel in [
            "plugins/llm-wiki-client-claude/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client-opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]:
            text = (temp_root / rel).read_text(encoding="utf-8")
            with self.subTest(rel=rel):
                self.assertTrue(text.startswith("---\n"), rel)
                self.assertIn("Generated by scripts/sync_adapters.py", text)


if __name__ == "__main__":
    unittest.main()
