from pathlib import Path
import json
import re
import subprocess
import unittest


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKDOWN_MARKER = "<!-- Generated by scripts/sync_adapters.py; do not edit by hand. -->"


class SourceLayoutTests(unittest.TestCase):
    def test_version_and_constants_exist(self):
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        constants = json.loads((ROOT / "src/shared/constants.json").read_text(encoding="utf-8"))
        self.assertRegex(version, r"^\d+\.\d+\.\d+$")
        self.assertEqual(constants["version"], version)
        self.assertEqual(constants["plugin_name"], "llm-wiki-client")
        self.assertEqual(constants["marketplace_name"], "llm-wiki-cloud")
        self.assertEqual(constants["mcp_url"], "https://wiki.andykong.top/mcp")
        self.assertEqual(constants["backflow_upload_url"], "https://wiki.andykong.top/upload/backflow")
        self.assertEqual(constants["version_manifest_url"], "https://wiki.andykong.top/plugin/llm-wiki-client/version.json")

    def test_pin_block_template_has_platform_slots(self):
        text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("{{instruction_file}}", text)
        self.assertIn("{{mcp_url}}", text)
        self.assertIn("{{query_skill_name}}", text)
        self.assertIn("{{wiki_search_tool}}", text)
        self.assertIn("{{wiki_get_page_tool}}", text)


class TemplateInventoryTests(unittest.TestCase):
    def test_skill_templates_do_not_reference_legacy_query_skill(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("llm-wiki-query", text, path.relative_to(ROOT))

    def test_shared_skill_templates_are_platform_neutral(self):
        forbidden_phrases = [
            "当前 Claude Code 项目目录",
            "/plugin update",
            "/reload-plugins",
            "claude mcp add",
        ]
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            for phrase in forbidden_phrases:
                with self.subTest(path=path.relative_to(ROOT), phrase=phrase):
                    self.assertNotIn(phrase, text)

    def test_mount_template_uses_shared_pin_block_contract(self):
        mount_text = (ROOT / "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl").read_text(encoding="utf-8")
        pin_block_text = (ROOT / "src/shared/pin-block.md.tmpl").read_text(encoding="utf-8")
        self.assertIn("src/shared/pin-block.md.tmpl", mount_text)
        for slot in set(re.findall(r"{{[a-zA-Z0-9_]+}}", pin_block_text)):
            with self.subTest(slot=slot):
                self.assertIn(slot, mount_text)

    def test_skill_templates_have_no_todo_markers(self):
        for path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("TODO", text, path.relative_to(ROOT))

    def test_required_templates_exist(self):
        required = [
            "src/commands/wiki-cloud-mount.md.tmpl",
            "src/commands/wiki-cloud-backflow.md.tmpl",
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
            "platforms/claude/marketplace.json.tmpl",
            "platforms/claude/plugin.json.tmpl",
            "platforms/codex/marketplace.json.tmpl",
            "platforms/codex/plugin.json.tmpl",
            "platforms/opencode/opencode.json.tmpl",
            "platforms/opencode/install-opencode.sh.tmpl",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                path = ROOT / rel
                self.assertTrue(path.exists(), rel)
                self.assertGreater(path.stat().st_size, 80, rel)

    def test_skill_templates_have_required_frontmatter_slots(self):
        for rel in [
            "src/skills/llm-wiki-cloud-mount/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-query/SKILL.md.tmpl",
            "src/skills/llm-wiki-cloud-backflow/SKILL.md.tmpl",
        ]:
            text = (ROOT / rel).read_text(encoding="utf-8")
            self.assertIn("version: {{version}}", text)
            self.assertIn("name:", text)
            self.assertIn("description:", text)


class SyncAdaptersTests(unittest.TestCase):
    def run_sync(self):
        subprocess.run(["python3", "scripts/sync_adapters.py"], cwd=ROOT, check=True)

    def test_sync_preserves_unmanaged_agents_files(self):
        sentinel = ROOT / ".agents/unmanaged/sentinel.txt"
        sentinel_text = "unmanaged agent state must survive sync\n"
        sentinel.parent.mkdir(parents=True, exist_ok=True)
        sentinel.write_text(sentinel_text, encoding="utf-8")

        try:
            self.run_sync()

            self.assertTrue(sentinel.exists())
            self.assertEqual(sentinel.read_text(encoding="utf-8"), sentinel_text)
        finally:
            sentinel.unlink(missing_ok=True)
            try:
                sentinel.parent.rmdir()
            except OSError:
                pass

    def test_sync_removes_stale_generated_marked_files(self):
        stale_generated = ROOT / "plugins/llm-wiki-client/commands/stale-generated.md"
        stale_user = ROOT / "plugins/llm-wiki-client/commands/stale-user.md"
        stale_generated.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated command\n", encoding="utf-8")
        stale_user.write_text("user managed command\n", encoding="utf-8")

        try:
            self.run_sync()

            self.assertFalse(stale_generated.exists())
            self.assertTrue(stale_user.exists())
        finally:
            stale_generated.unlink(missing_ok=True)
            stale_user.unlink(missing_ok=True)

    def test_sync_removes_stale_generated_skill_files(self):
        stale_skill = ROOT / "plugins/llm-wiki-client/skills/stale/SKILL.md"
        stale_skill.parent.mkdir(parents=True, exist_ok=True)
        stale_skill.write_text(f"{GENERATED_MARKDOWN_MARKER}\n\nold generated skill\n", encoding="utf-8")

        try:
            self.run_sync()

            self.assertFalse(stale_skill.exists())
        finally:
            stale_skill.unlink(missing_ok=True)
            try:
                stale_skill.parent.rmdir()
            except OSError:
                pass

    def test_sync_generates_all_platform_entrypoints(self):
        self.run_sync()
        required = [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client/.mcp.json",
            "plugins/llm-wiki-client/commands/wiki-cloud-mount.md",
            "plugins/llm-wiki-client/commands/wiki-cloud-backflow.md",
            "plugins/llm-wiki-client/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client/skills/llm-wiki-cloud-backflow/SKILL.md",
            "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-query/SKILL.md",
            "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-backflow/SKILL.md",
            "dist/opencode/opencode.json",
            "dist/opencode/install-opencode.sh",
            "dist/opencode/.opencode/commands/wiki-cloud-mount.md",
            "dist/opencode/.opencode/commands/wiki-cloud-backflow.md",
            "dist/opencode/.opencode/skills/llm-wiki-cloud-mount/SKILL.md",
            "dist/opencode/.opencode/skills/llm-wiki-cloud-query/SKILL.md",
            "dist/opencode/.opencode/skills/llm-wiki-cloud-backflow/SKILL.md",
        ]
        for rel in required:
            with self.subTest(rel=rel):
                self.assertTrue((ROOT / rel).exists(), rel)

    def test_sync_replaces_all_template_variables(self):
        self.run_sync()
        generated = [
            "plugins/llm-wiki-client/skills/llm-wiki-cloud-mount/SKILL.md",
            "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-mount/SKILL.md",
            "dist/opencode/.opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]
        for rel in generated:
            path = ROOT / rel
            self.assertTrue(path.exists(), rel)
            text = path.read_text(encoding="utf-8")
            self.assertNotIn("{{", text)
            self.assertNotIn("}}", text)
            self.assertIn("version: 1.1.6", text)
            self.assertIn("https://wiki.andykong.top/mcp", text)

    def test_sync_generates_platform_specific_instruction_targets(self):
        self.run_sync()
        claude_mount = (ROOT / "plugins/llm-wiki-client/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        codex_mount_path = ROOT / "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        opencode_mount = (ROOT / "dist/opencode/.opencode/skills/llm-wiki-cloud-mount/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("CLAUDE.md", claude_mount)
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("AGENTS.md", opencode_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", opencode_mount)

    def test_sync_generates_codex_specific_skill_root(self):
        self.run_sync()
        codex_manifest = json.loads(
            (ROOT / "plugins/llm-wiki-client/.codex-plugin/plugin.json").read_text(encoding="utf-8")
        )
        self.assertIn("skills", codex_manifest)
        self.assertEqual(codex_manifest["skills"], "./codex/skills/")

        codex_mount_path = ROOT / "plugins/llm-wiki-client/codex/skills/llm-wiki-cloud-mount/SKILL.md"
        self.assertTrue(codex_mount_path.exists())
        codex_mount = codex_mount_path.read_text(encoding="utf-8")
        self.assertIn("AGENTS.md", codex_mount)
        self.assertIn("cann-infer-wiki-cloud wiki_search", codex_mount)
        self.assertNotIn("CLAUDE.md", codex_mount)
        self.assertNotIn("mcp__plugin_llm-wiki-client", codex_mount)

    def test_sync_generates_valid_json_manifests(self):
        self.run_sync()
        for rel in [
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "plugins/llm-wiki-client/.claude-plugin/plugin.json",
            "plugins/llm-wiki-client/.codex-plugin/plugin.json",
            "plugins/llm-wiki-client/.mcp.json",
            "dist/opencode/opencode.json",
        ]:
            with self.subTest(rel=rel):
                json.loads((ROOT / rel).read_text(encoding="utf-8"))

    def test_sync_preserves_markdown_frontmatter(self):
        self.run_sync()
        for rel in [
            "plugins/llm-wiki-client/commands/wiki-cloud-mount.md",
            "plugins/llm-wiki-client/skills/llm-wiki-cloud-mount/SKILL.md",
            "dist/opencode/.opencode/commands/wiki-cloud-mount.md",
            "dist/opencode/.opencode/skills/llm-wiki-cloud-mount/SKILL.md",
        ]:
            text = (ROOT / rel).read_text(encoding="utf-8")
            with self.subTest(rel=rel):
                self.assertTrue(text.startswith("---\n"), rel)
                self.assertIn("Generated by scripts/sync_adapters.py", text)


if __name__ == "__main__":
    unittest.main()
