#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
from pathlib import Path


ROOT = Path(os.environ.get("LLM_WIKI_REPO_ROOT", Path(__file__).resolve().parents[1])).resolve()
GENERATED_MARKDOWN_MARKER = "<!-- Generated by scripts/sync_adapters.py; do not edit by hand. -->"
TEMPLATE_SLOT_RE = re.compile(r"{{([a-zA-Z0-9_]+)}}")
GENERATED_JSON_OUTPUTS = [
    ".agents/plugins/marketplace.json",
    "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
    "plugins/llm-wiki-client-claude/.mcp.json",
    "plugins/llm-wiki-client-opencode/opencode.json",
    # Legacy generated paths kept here so sync removes stale files after layout changes.
    "plugins/llm-wiki-client/.mcp.json",
    "plugins/llm-wiki-client/.codex-plugin/plugin.json",
    "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
    "plugins/llm-wiki-client-codex/.mcp.json",
    ".claude-plugin/marketplace.json",
    "plugins/llm-wiki-client/.claude-plugin/plugin.json",
    "dist/opencode/opencode.json",
]
GENERATED_DIRECT_OUTPUTS = [
    "dist/opencode/bootstrap.sh",
    "dist/opencode/install-opencode.sh",
    "dist/opencode/uninstall.sh",
]
GENERATED_MARKER_CLEANUP_DIRS = [
    "plugins/llm-wiki-client-claude/skills",
    "plugins/llm-wiki-client/commands",
    "plugins/llm-wiki-client/skills",
    "plugins/llm-wiki-client/codex/skills",
    "plugins/llm-wiki-client-codex/skills",
    "plugins/llm-wiki-client-opencode/skills",
    "dist/opencode/.opencode/commands",
    "dist/opencode/.opencode/skills",
]
MANAGED_SKILL_NAMES = {
    "llm-wiki-cloud-mount",
    "llm-wiki-cloud-query",
    "llm-wiki-cloud-backflow",
}
GENERATED_SKILL_ROOTS = [
    "plugins/llm-wiki-client-claude/skills",
    "plugins/llm-wiki-client-codex/skills",
    "plugins/llm-wiki-client-opencode/skills",
]


def load_values() -> dict[str, str]:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    constants = json.loads((ROOT / "src/shared/constants.json").read_text(encoding="utf-8"))
    if constants.get("version") != version:
        raise ValueError("VERSION and src/shared/constants.json disagree")

    values = {key: str(value) for key, value in constants.items()}
    values["version"] = version
    values["query_skill_name"] = "llm-wiki-cloud-query"
    return values


def platform_values(base: dict[str, str], platform: str) -> dict[str, str]:
    values = dict(base)
    values["platform"] = platform

    if platform == "claude":
        values.update(
            {
                "instruction_file": "CLAUDE.md",
                "wiki_search_tool": "mcp__plugin_llm-wiki-client_cann-infer-wiki-cloud__wiki_search",
                "wiki_get_page_tool": "mcp__plugin_llm-wiki-client_cann-infer-wiki-cloud__wiki_get_page",
                "project_context_label": "当前 Claude Code 项目",
                "workspace_root_phrase": "当前 Claude Code 项目目录",
                "mcp_config_summary": "MCP 客户端配置由插件 root 的 `.mcp.json` 自带，安装插件后自动注册：",
                "mcp_mutation_guard": "本 skill 不 clone wiki 仓、不启动本机 server、不写 `.mcp.json`、不调用 `claude mcp add`。",
            }
        )
    elif platform in {"codex", "opencode"}:
        values.update(
            {
                "instruction_file": "AGENTS.md",
                "wiki_search_tool": "cann-infer-wiki-cloud wiki_search",
                "wiki_get_page_tool": "cann-infer-wiki-cloud wiki_get_page",
                "project_context_label": "当前项目",
                "workspace_root_phrase": "当前项目根目录",
                "mcp_config_summary": "MCP 客户端配置由当前平台 adapter 提供：",
                "mcp_mutation_guard": "本 skill 不 clone wiki 仓、不启动本机 server、不修改平台 MCP 配置、不调用本地 MCP 注册命令。",
            }
        )
    else:
        raise ValueError(f"unknown platform: {platform}")

    return values


def render_template(template_path: Path, values: dict[str, str]) -> str:
    template = template_path.read_text(encoding="utf-8")

    def replace_slot(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            raise KeyError(f"{template_path.relative_to(ROOT)} references unknown template key: {key}")
        return values[key]

    rendered = TEMPLATE_SLOT_RE.sub(replace_slot, template)
    if "{{" in rendered or "}}" in rendered:
        raise ValueError(f"unrendered template marker in {template_path.relative_to(ROOT)}")
    return rendered


def with_pin_block(values: dict[str, str]) -> dict[str, str]:
    values = dict(values)
    values["pin_block"] = render_template(ROOT / "src/shared/pin-block.md.tmpl", values).rstrip()
    return values


def ensure_trailing_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ensure_trailing_newline(text), encoding="utf-8")


def write_rendered_template(
    template_rel: str,
    output_rel: str,
    values: dict[str, str],
    *,
    validate_json: bool = False,
) -> None:
    rendered = render_template(ROOT / template_rel, values)
    if validate_json:
        json.loads(rendered)
    write_text(ROOT / output_rel, rendered)


def contains_generated_marker(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    return GENERATED_MARKDOWN_MARKER in text


def unlink_known_file(path: Path) -> None:
    if path.is_file() or path.is_symlink():
        path.unlink()


def prune_empty_dirs(path: Path, stop: Path) -> None:
    while path != stop and path != ROOT:
        try:
            path.rmdir()
        except OSError:
            return
        path = path.parent


def clean_generated_files_with_markers(root: Path) -> None:
    if not root.exists():
        return
    for path in sorted(root.rglob("*"), reverse=True):
        if not path.is_file() or path.is_symlink():
            continue
        if contains_generated_marker(path):
            path.unlink()
            prune_empty_dirs(path.parent, root.parent)


def clean_generated_dirs() -> None:
    for rel in [*GENERATED_JSON_OUTPUTS, *GENERATED_DIRECT_OUTPUTS]:
        unlink_known_file(ROOT / rel)

    for rel in GENERATED_MARKER_CLEANUP_DIRS:
        clean_generated_files_with_markers(ROOT / rel)

    for root_rel in GENERATED_SKILL_ROOTS:
        root = ROOT / root_rel
        for skill_name in MANAGED_SKILL_NAMES:
            unlink_known_file(root / skill_name / "SKILL.md")
            prune_empty_dirs(root / skill_name, root)

    prune_empty_dirs(ROOT / "dist/opencode", ROOT / "dist")


def generate_manifests(base_values: dict[str, str]) -> None:
    claude = platform_values(base_values, "claude")
    codex = platform_values(base_values, "codex")
    opencode = platform_values(base_values, "opencode")

    write_rendered_template(
        "platforms/claude/marketplace.json.tmpl",
        ".claude-plugin/marketplace.json",
        claude,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/claude/plugin.json.tmpl",
        "plugins/llm-wiki-client-claude/.claude-plugin/plugin.json",
        claude,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/codex/marketplace.json.tmpl",
        ".agents/plugins/marketplace.json",
        codex,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/codex/plugin.json.tmpl",
        "plugins/llm-wiki-client-codex/.codex-plugin/plugin.json",
        codex,
        validate_json=True,
    )

    mcp_config = {
        "mcpServers": {
            base_values["mcp_server_name"]: {
                "type": "http",
                "url": base_values["mcp_url"],
            }
        }
    }
    write_text(
        ROOT / "plugins/llm-wiki-client-claude/.mcp.json",
        json.dumps(mcp_config, ensure_ascii=False, indent=2),
    )
    write_text(
        ROOT / "plugins/llm-wiki-client-codex/.mcp.json",
        json.dumps(mcp_config, ensure_ascii=False, indent=2),
    )

    write_rendered_template(
        "platforms/opencode/opencode.json.tmpl",
        "plugins/llm-wiki-client-opencode/opencode.json",
        opencode,
        validate_json=True,
    )


def generate_skills(values: dict[str, str], output_root: str) -> None:
    for template_path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
        skill_name = template_path.parent.name
        rendered = render_template(template_path, values)
        write_text(ROOT / output_root / skill_name / "SKILL.md", rendered)


def main() -> None:
    base_values = load_values()
    claude = with_pin_block(platform_values(base_values, "claude"))
    codex = with_pin_block(platform_values(base_values, "codex"))
    opencode = with_pin_block(platform_values(base_values, "opencode"))

    clean_generated_dirs()
    generate_manifests(base_values)
    generate_skills(claude, "plugins/llm-wiki-client-claude/skills")
    generate_skills(codex, "plugins/llm-wiki-client-codex/skills")
    generate_skills(opencode, "plugins/llm-wiki-client-opencode/skills")


if __name__ == "__main__":
    main()
