#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import stat
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKDOWN_MARKER = "<!-- Generated by scripts/sync_adapters.py; do not edit by hand. -->"
GENERATED_SHELL_MARKER = "# Generated by scripts/sync_adapters.py; do not edit by hand."
TEMPLATE_SLOT_RE = re.compile(r"{{([a-zA-Z0-9_]+)}}")
EXECUTABLE_MODE = stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
GENERATED_JSON_OUTPUTS = [
    ".agents/plugins/marketplace.json",
    "plugins/llm-wiki-client/.codex-plugin/plugin.json",
    "plugins/llm-wiki-client/.mcp.json",
    ".claude-plugin/marketplace.json",
    "plugins/llm-wiki-client/.claude-plugin/plugin.json",
    "dist/opencode/opencode.json",
]
GENERATED_DIRECT_OUTPUTS = [
    "dist/opencode/install-opencode.sh",
]
GENERATED_MARKER_CLEANUP_DIRS = [
    "plugins/llm-wiki-client/commands",
    "plugins/llm-wiki-client/skills",
    "plugins/llm-wiki-client/codex/skills",
    "dist/opencode/.opencode/commands",
    "dist/opencode/.opencode/skills",
]


def load_values() -> dict[str, str]:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    constants = json.loads((ROOT / "src/shared/constants.json").read_text(encoding="utf-8"))
    if constants.get("version") != version:
        raise ValueError("VERSION and src/shared/constants.json disagree")

    values = {key: str(value) for key, value in constants.items()}
    values["version"] = version
    values["query_skill_name"] = "llm-wiki-cloud-query"
    return values


def platform_values(base: dict[str, str], platform: str) -> dict[str, str]:
    values = dict(base)
    values["platform"] = platform

    if platform == "claude":
        values.update(
            {
                "instruction_file": "CLAUDE.md",
                "wiki_search_tool": "mcp__plugin_llm-wiki-client_cann-infer-wiki-cloud__wiki_search",
                "wiki_get_page_tool": "mcp__plugin_llm-wiki-client_cann-infer-wiki-cloud__wiki_get_page",
            }
        )
    elif platform in {"codex", "opencode"}:
        values.update(
            {
                "instruction_file": "AGENTS.md",
                "wiki_search_tool": "cann-infer-wiki-cloud wiki_search",
                "wiki_get_page_tool": "cann-infer-wiki-cloud wiki_get_page",
            }
        )
    else:
        raise ValueError(f"unknown platform: {platform}")

    return values


def render_template(template_path: Path, values: dict[str, str]) -> str:
    template = template_path.read_text(encoding="utf-8")

    def replace_slot(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            raise KeyError(f"{template_path.relative_to(ROOT)} references unknown template key: {key}")
        return values[key]

    rendered = TEMPLATE_SLOT_RE.sub(replace_slot, template)
    if "{{" in rendered or "}}" in rendered:
        raise ValueError(f"unrendered template marker in {template_path.relative_to(ROOT)}")
    return rendered


def ensure_trailing_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def with_markdown_marker(text: str) -> str:
    text = ensure_trailing_newline(text)
    if text.startswith("---\n"):
        frontmatter_end = text.find("\n---\n", 4)
        if frontmatter_end != -1:
            insert_at = frontmatter_end + len("\n---\n")
            return f"{text[:insert_at]}\n{GENERATED_MARKDOWN_MARKER}\n\n{text[insert_at:]}"
    return f"{GENERATED_MARKDOWN_MARKER}\n\n{text}"


def with_shell_marker(text: str) -> str:
    text = ensure_trailing_newline(text)
    lines = text.splitlines(keepends=True)
    if lines and lines[0].startswith("#!"):
        return "".join([lines[0], f"{GENERATED_SHELL_MARKER}\n", *lines[1:]])
    return f"{GENERATED_SHELL_MARKER}\n{text}"


def write_text(path: Path, text: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ensure_trailing_newline(text), encoding="utf-8")
    if mode is not None:
        path.chmod(mode)


def write_rendered_template(
    template_rel: str,
    output_rel: str,
    values: dict[str, str],
    *,
    markdown_marker: bool = False,
    shell_marker: bool = False,
    executable: bool = False,
    validate_json: bool = False,
) -> None:
    rendered = render_template(ROOT / template_rel, values)
    if validate_json:
        json.loads(rendered)
    if markdown_marker:
        rendered = with_markdown_marker(rendered)
    if shell_marker:
        rendered = with_shell_marker(rendered)
    write_text(ROOT / output_rel, rendered, EXECUTABLE_MODE if executable else None)


def contains_generated_marker(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    return GENERATED_MARKDOWN_MARKER in text or GENERATED_SHELL_MARKER in text


def unlink_known_file(path: Path) -> None:
    if path.is_file() or path.is_symlink():
        path.unlink()


def prune_empty_dirs(path: Path, stop: Path) -> None:
    while path != stop and path != ROOT:
        try:
            path.rmdir()
        except OSError:
            return
        path = path.parent


def clean_generated_files_with_markers(root: Path) -> None:
    if not root.exists():
        return
    for path in sorted(root.rglob("*"), reverse=True):
        if not path.is_file() or path.is_symlink():
            continue
        if contains_generated_marker(path):
            path.unlink()
            prune_empty_dirs(path.parent, root.parent)


def clean_generated_dirs() -> None:
    for rel in [*GENERATED_JSON_OUTPUTS, *GENERATED_DIRECT_OUTPUTS]:
        unlink_known_file(ROOT / rel)

    for rel in GENERATED_MARKER_CLEANUP_DIRS:
        clean_generated_files_with_markers(ROOT / rel)

    prune_empty_dirs(ROOT / "dist/opencode", ROOT / "dist")


def generate_manifests(base_values: dict[str, str]) -> None:
    claude = platform_values(base_values, "claude")
    codex = platform_values(base_values, "codex")
    opencode = platform_values(base_values, "opencode")

    write_rendered_template(
        "platforms/claude/marketplace.json.tmpl",
        ".claude-plugin/marketplace.json",
        claude,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/claude/plugin.json.tmpl",
        "plugins/llm-wiki-client/.claude-plugin/plugin.json",
        claude,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/codex/marketplace.json.tmpl",
        ".agents/plugins/marketplace.json",
        codex,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/codex/plugin.json.tmpl",
        "plugins/llm-wiki-client/.codex-plugin/plugin.json",
        codex,
        validate_json=True,
    )

    mcp_config = {
        "mcpServers": {
            base_values["mcp_server_name"]: {
                "type": "http",
                "url": base_values["mcp_url"],
            }
        }
    }
    write_text(
        ROOT / "plugins/llm-wiki-client/.mcp.json",
        json.dumps(mcp_config, ensure_ascii=False, indent=2),
    )

    write_rendered_template(
        "platforms/opencode/opencode.json.tmpl",
        "dist/opencode/opencode.json",
        opencode,
        validate_json=True,
    )
    write_rendered_template(
        "platforms/opencode/install-opencode.sh.tmpl",
        "dist/opencode/install-opencode.sh",
        opencode,
        shell_marker=True,
        executable=True,
    )


def generate_commands(values: dict[str, str], output_root: str) -> None:
    for template_path in sorted((ROOT / "src/commands").glob("*.md.tmpl")):
        output_name = template_path.name.removesuffix(".tmpl")
        rendered = render_template(template_path, values)
        write_text(ROOT / output_root / output_name, with_markdown_marker(rendered))


def generate_skills(values: dict[str, str], output_root: str) -> None:
    for template_path in sorted((ROOT / "src/skills").glob("*/SKILL.md.tmpl")):
        skill_name = template_path.parent.name
        rendered = render_template(template_path, values)
        write_text(ROOT / output_root / skill_name / "SKILL.md", with_markdown_marker(rendered))


def main() -> None:
    base_values = load_values()
    claude = platform_values(base_values, "claude")
    codex = platform_values(base_values, "codex")
    opencode = platform_values(base_values, "opencode")

    clean_generated_dirs()
    generate_manifests(base_values)
    generate_commands(claude, "plugins/llm-wiki-client/commands")
    generate_commands(opencode, "dist/opencode/.opencode/commands")
    generate_skills(claude, "plugins/llm-wiki-client/skills")
    generate_skills(codex, "plugins/llm-wiki-client/codex/skills")
    generate_skills(opencode, "dist/opencode/.opencode/skills")


if __name__ == "__main__":
    main()
